# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 977d2b5b4a8f9c60f6aded4a76c98170794782e9ee077350531b1cb95a01dc136de9099b10e039521aedd1f31c4f4fba42246e1ea0379768e42b0739a9fd266f

test:
  secret_key_base: 5c3180bb0a33257436f61e9cda29ba74fd1c34c7ba767426ddb710a70d03817f5657e7b0fd649e24710556a3a1b319136eba7d626c39d073db4aa29ad8aaf3d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
